import Head from "next/head";
import "./globals.css";
import Script from "next/script";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
      </Head>
      <body className="">
        {/* Navbar  */}
        <nav className="h-14"></nav>
        {/* main */}
        {children}
        
      </body>
    </html>
  );
}
